//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPR.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACPR.Ressources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 3.11 réussi.
        /// </summary>
        internal static string ActifsAffecteChamp3_11Reussite {
            get {
                return ResourceManager.GetString("ActifsAffecteChamp3_11Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les valeurs du champ 3.12 ne correspondent pas à celles possibles.
        /// </summary>
        internal static string ActifsAffecteChamp3_12NonConforme {
            get {
                return ResourceManager.GetString("ActifsAffecteChamp3_12NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.12 ne peut pas etre vide en cas de rapport intermediaire ou final.
        /// </summary>
        internal static string ActifsAffecteChamp3_12Obligatoire {
            get {
                return ResourceManager.GetString("ActifsAffecteChamp3_12Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 3.12 réussi.
        /// </summary>
        internal static string ActifsAffecteChamp3_12Reussite {
            get {
                return ResourceManager.GetString("ActifsAffecteChamp3_12Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le champ 3.6 et 3.7 sont obligatoire en cas de rapport intermediaire ou final.
        /// </summary>
        internal static string ActifsAffecteChamp3_6_3_7Obligatoire {
            get {
                return ResourceManager.GetString("ActifsAffecteChamp3_6-3_7Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des champs 3.6 et 3.7 réussi.
        /// </summary>
        internal static string ActifsAffecteChamp3_6_3_7Reussite {
            get {
                return ResourceManager.GetString("ActifsAffecteChamp3_6_3_7Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs 3.10 et 3.11 sont obligatoires si le champs 3.9 &gt; 0.
        /// </summary>
        internal static string ActifsAffecteChamps3_10_3_11Obligatoire {
            get {
                return ResourceManager.GetString("ActifsAffecteChamps3_10_3_11Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs 3.4 et 3.5 sont obligatoires en cas de rapport intermédiaire ou final.
        /// </summary>
        internal static string ActifsAffecteChamps3_4_3_5Obligatoire {
            get {
                return ResourceManager.GetString("ActifsAffecteChamps3_4_3_5Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des champs 3.4 et 3.5 réussi.
        /// </summary>
        internal static string ActifsAffecteChamps3_4_3_5Reussite {
            get {
                return ResourceManager.GetString("ActifsAffecteChamps3_4_3_5Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des champs 3.9, 3.10 et 3.11 réussi.
        /// </summary>
        internal static string ActifsAffecteChamps3_9_3_10_3_11Reussite {
            get {
                return ResourceManager.GetString("ActifsAffecteChamps3_9_3_10_3_11Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la lecture des champs 3.4 et 3.5.
        /// </summary>
        internal static string ActifsAffecteErreur3_4_3_5 {
            get {
                return ResourceManager.GetString("ActifsAffecteErreur3_4_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la lecture des champs 3.6 et 3.7.
        /// </summary>
        internal static string ActifsAffecteErreur3_6_3_7 {
            get {
                return ResourceManager.GetString("ActifsAffecteErreur3_6_3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la lecture des champs 3.9 et 3.10.
        /// </summary>
        internal static string ActifsAffecteErreur3_9_3_10 {
            get {
                return ResourceManager.GetString("ActifsAffecteErreur3_9_3_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du parse du champ 3.11.
        /// </summary>
        internal static string ActifsAffecteParse3_11 {
            get {
                return ResourceManager.GetString("ActifsAffecteParse3_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du parse du champ 3.9.
        /// </summary>
        internal static string ActifsAffecteParse3_9 {
            get {
                return ResourceManager.GetString("ActifsAffecteParse3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reussite création ActifsAffecte.
        /// </summary>
        internal static string ActifsAffecteReussite {
            get {
                return ResourceManager.GetString("ActifsAffecteReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs 2.6 ne respectent pas les variables attendus.
        /// </summary>
        internal static string ClassificationChamp2_5NonConforme {
            get {
                return ResourceManager.GetString("ClassificationChamp2_5NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le critere de classification est obligatoire.
        /// </summary>
        internal static string ClassificationChamp2_5Obligatoire {
            get {
                return ResourceManager.GetString("ClassificationChamp2_5Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 2.5 réussi.
        /// </summary>
        internal static string ClassificationChamp2_5Reussite {
            get {
                return ResourceManager.GetString("ClassificationChamp2_5Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.6 ne respecte pas les valeurs attendus.
        /// </summary>
        internal static string ClassificationChamp2_6NonConforme {
            get {
                return ResourceManager.GetString("ClassificationChamp2_6NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cas de critere de classification Geographical Spread, le champ 2.6 est obligatoire.
        /// </summary>
        internal static string ClassificationChamp2_6Obligatoire {
            get {
                return ResourceManager.GetString("ClassificationChamp2_6Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 2.6 réussi.
        /// </summary>
        internal static string ClassificationChamp2_6Reussite {
            get {
                return ResourceManager.GetString("ClassificationChamp2_6Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cas de critere de classification Reputational Impact, les elements 3.13 et 3.14 sont obligatoires.
        /// </summary>
        internal static string ClassificationChamp3_13_3_14Obligatoire {
            get {
                return ResourceManager.GetString("ClassificationChamp3_13_3_14Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des champs 3.13 et 3.14 réussi.
        /// </summary>
        internal static string ClassificationChamp3_13_3_14Reussite {
            get {
                return ResourceManager.GetString("ClassificationChamp3_13_3_14Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.13 ne respecte pas les variables attendus.
        /// </summary>
        internal static string ClassificationChamp3_13NonConforme {
            get {
                return ResourceManager.GetString("ClassificationChamp3_13NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs 3.18 et 3.19 sont obligatoires en cas de Classification geographical_spread pour les rapports intermediaires et finaux.
        /// </summary>
        internal static string ClassificationChamp3_18_3_19Obligatoire {
            get {
                return ResourceManager.GetString("ClassificationChamp3_18_3_19Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des champs 3.18 et 3.19 réussi.
        /// </summary>
        internal static string ClassificationChamp3_18_3_19Reussite {
            get {
                return ResourceManager.GetString("ClassificationChamp3_18_3_19Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3_18 ne correspondant pas aux valeurs attendus.
        /// </summary>
        internal static string ClassificationChamp3_18NonConforme {
            get {
                return ResourceManager.GetString("ClassificationChamp3_18NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cas de critere de classification Data losses, les elements 3.20 et 3.21 sont obligatoires.
        /// </summary>
        internal static string ClassificationChamp3_20_3_21Obligatoire {
            get {
                return ResourceManager.GetString("ClassificationChamp3_20_3_21Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des champs 3.20 et 3.21 réussi.
        /// </summary>
        internal static string ClassificationChamp3_20_3_21Reussite {
            get {
                return ResourceManager.GetString("ClassificationChamp3_20_3_21Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champs 3.20 ne respecte pas les variables attendus.
        /// </summary>
        internal static string ClassificationChamp3_20NonConforme {
            get {
                return ResourceManager.GetString("ClassificationChamp3_20NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.12 doit etre renseigné pour les rapports finaux.
        /// </summary>
        internal static string ClassificationChamp4_12Obligatoire {
            get {
                return ResourceManager.GetString("ClassificationChamp4_12Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 4.12 réussi.
        /// </summary>
        internal static string ClassificationChamp4_12Reussite {
            get {
                return ResourceManager.GetString("ClassificationChamp4_12Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reussite création Classification.
        /// </summary>
        internal static string ClassificationReussite {
            get {
                return ResourceManager.GetString("ClassificationReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email non conforme.
        /// </summary>
        internal static string ContactEmailNonConforme {
            get {
                return ResourceManager.GetString("ContactEmailNonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;email du contact est obligatoire.
        /// </summary>
        internal static string ContactEmailObligatoire {
            get {
                return ResourceManager.GetString("ContactEmailObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture email Contact réussi.
        /// </summary>
        internal static string ContactEmailReussite {
            get {
                return ResourceManager.GetString("ContactEmailReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du contact est obligatoire.
        /// </summary>
        internal static string ContactNomObligatoire {
            get {
                return ResourceManager.GetString("ContactNomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture nom Contact réussi.
        /// </summary>
        internal static string ContactNomReussite {
            get {
                return ResourceManager.GetString("ContactNomReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reussite création Contact.
        /// </summary>
        internal static string ContactReussite {
            get {
                return ResourceManager.GetString("ContactReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de télephone non conforme.
        /// </summary>
        internal static string ContactTelNonConforme {
            get {
                return ResourceManager.GetString("ContactTelNonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de télephone du contact est obligatoire.
        /// </summary>
        internal static string ContactTelObligatoire {
            get {
                return ResourceManager.GetString("ContactTelObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture numéro de téléphone Contact réussi.
        /// </summary>
        internal static string ContactTelReussite {
            get {
                return ResourceManager.GetString("ContactTelReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type de l&apos;entite ne respecte pas les choix demandés.
        /// </summary>
        internal static string EntiteAffecteTypeNonConforme {
            get {
                return ResourceManager.GetString("EntiteAffecteTypeNonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type de l&apos;entité affecte doit etre renseigne.
        /// </summary>
        internal static string EntiteAffecteTypeObligatoire {
            get {
                return ResourceManager.GetString("EntiteAffecteTypeObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture type EntiteAffecté réussi.
        /// </summary>
        internal static string EntiteAffecteTypeReussite {
            get {
                return ResourceManager.GetString("EntiteAffecteTypeReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture code Entite réussi.
        /// </summary>
        internal static string EntiteCodeReussite {
            get {
                return ResourceManager.GetString("EntiteCodeReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code LEI et le code EU ID d&apos;une entité ne peuvent pas etre null tout les deux..
        /// </summary>
        internal static string EntiteLei_EUIDNull {
            get {
                return ResourceManager.GetString("EntiteLei_EUIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code lei non conforme.
        /// </summary>
        internal static string EntiteLeiNonConforme {
            get {
                return ResourceManager.GetString("EntiteLeiNonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code LEI de l&apos;entité ne peut pas etre null.
        /// </summary>
        internal static string EntiteLeiObligatoire {
            get {
                return ResourceManager.GetString("EntiteLeiObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom de l&apos;entité ne peut pas etre null.
        /// </summary>
        internal static string EntiteNomObligatoire {
            get {
                return ResourceManager.GetString("EntiteNomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture nom Entité réussi.
        /// </summary>
        internal static string EntiteNomReussite {
            get {
                return ResourceManager.GetString("EntiteNomReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite création Entité.
        /// </summary>
        internal static string EntiteReussite {
            get {
                return ResourceManager.GetString("EntiteReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type d&apos;entité rentré n&apos;est pas un type d&apos;entite valide.
        /// </summary>
        internal static string EntiteTypeNonConforme {
            get {
                return ResourceManager.GetString("EntiteTypeNonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type de l&apos;entité est obligatoire.
        /// </summary>
        internal static string EntiteTypeObligatoire {
            get {
                return ResourceManager.GetString("EntiteTypeObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture type Entite réussi.
        /// </summary>
        internal static string EntiteTypeReussite {
            get {
                return ResourceManager.GetString("EntiteTypeReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle Erreur : .
        /// </summary>
        internal static string ErreurLog {
            get {
                return ResourceManager.GetString("ErreurLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à erreur enfant : .
        /// </summary>
        internal static string ErreurLogEnfant {
            get {
                return ResourceManager.GetString("ErreurLogEnfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.22 est obligatoire pour les rapports intermediaires et finaux.
        /// </summary>
        internal static string EvaluationImpactChamp3_22Obligatoire {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_22Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.22 réussi.
        /// </summary>
        internal static string EvaluationImpactChamp3_22Reussite {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_22Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.27 est obligatoire pour les rapports intermediaires et finaux.
        /// </summary>
        internal static string EvaluationImpactChamp3_27Obligatoire {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_27Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.27 réussi.
        /// </summary>
        internal static string EvaluationImpactChamp3_27Reussite {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_27Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.28 ne respectent pas les valeurs possibles.
        /// </summary>
        internal static string EvaluationImpactChamp3_28NonConforme {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_28NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.28 est obligatoire pour les rapports intermediaires et finaux.
        /// </summary>
        internal static string EvaluationImpactChamp3_28Obligatoire {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_28Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.28 réussi.
        /// </summary>
        internal static string EvaluationImpactChamp3_28Reussite {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_28Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.29 est obligatoire si le champ 3.28 indique yes.
        /// </summary>
        internal static string EvaluationImpactChamp3_29Obligatoire {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_29Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.29 réussi.
        /// </summary>
        internal static string EvaluationImpactChamp3_29Reussite {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_29Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.30 est obligatoire pour les rapports intermediaires et finaux.
        /// </summary>
        internal static string EvaluationImpactChamp3_30Obligatoire {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_30Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.30 réussi.
        /// </summary>
        internal static string EvaluationImpactChamp3_30Reussite {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_30Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.8 est obligatoire pour les rapports intermediaires et finaux si le champ 2.5 a renseigné &quot;Client, financiel counterparts and transactions affected&quot;.
        /// </summary>
        internal static string EvaluationImpactChamp3_8Obligatoire {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_8Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.8 réussi.
        /// </summary>
        internal static string EvaluationImpactChamp3_8Reussite {
            get {
                return ResourceManager.GetString("EvaluationImpactChamp3_8Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite création EvaluationImpact.
        /// </summary>
        internal static string EvaluationImpactReussite {
            get {
                return ResourceManager.GetString("EvaluationImpactReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenu lors de la lecture du fichier..
        /// </summary>
        internal static string ExcelHelperErreurInatendu {
            get {
                return ResourceManager.GetString("ExcelHelperErreurInatendu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction données réussi de la page : .
        /// </summary>
        internal static string ExcelHelperExtractionReussite {
            get {
                return ResourceManager.GetString("ExcelHelperExtractionReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier renseigné est déja utilisé par un autre processus.
        /// </summary>
        internal static string ExcelHelperFichierDejaUtilise {
            get {
                return ResourceManager.GetString("ExcelHelperFichierDejaUtilise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le programme ne peux pas accéder au fichier, fichier introuvable, assurez vous d&apos;avoir renseigné le bon chemin/nom de fichier.
        /// </summary>
        internal static string ExcelHelperFichierNonTrouve {
            get {
                return ResourceManager.GetString("ExcelHelperFichierNonTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouverture fichier Excel réussi.
        /// </summary>
        internal static string ExcelHelperOuvertureReussite {
            get {
                return ResourceManager.GetString("ExcelHelperOuvertureReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mauvaise extension attendu. Veuillez revoir le format :.
        /// </summary>
        internal static string FichierHelperFormatFichierNonConforme {
            get {
                return ResourceManager.GetString("FichierHelperFormatFichierNonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier est introuvable. Veuillez vérifier le chemin pour y accéder.
        /// </summary>
        internal static string FichierHelperNonTrouve {
            get {
                return ResourceManager.GetString("FichierHelperNonTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la lecture du champs 3.16 : .
        /// </summary>
        internal static string ImpactServiceChamp3_16Erreur {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_16Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.16 réussi.
        /// </summary>
        internal static string ImpactServiceChamp3_16Reussite {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_16Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.33 est obligatoire pour les rapport intermediaire et finaux.
        /// </summary>
        internal static string ImpactServiceChamp3_33Obligatoire {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_33Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.34 est obligatoire si le champ 3.33 indique Yes.
        /// </summary>
        internal static string ImpactServiceChamp3_34Obligatoire {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_34Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date en champ 3.3 est invalide.
        /// </summary>
        internal static string ImpactServiceChamp3_3NonConforme {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_3NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.3 est obligatoire si la durée en 3.16 est supérieure à zero.
        /// </summary>
        internal static string ImpactServiceChamp3_3Obligatoire {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_3Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.3 réussi.
        /// </summary>
        internal static string ImpactServiceChamp3_3Reussite {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_3Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.4 réussi.
        /// </summary>
        internal static string ImpactServiceChamp3_4Reussite {
            get {
                return ResourceManager.GetString("ImpactServiceChamp3_4Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de lecture sur le champ 3.33.
        /// </summary>
        internal static string ImpactServiceErreur3_33 {
            get {
                return ResourceManager.GetString("ImpactServiceErreur3_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite création ImpactService.
        /// </summary>
        internal static string ImpactServiceReussite {
            get {
                return ResourceManager.GetString("ImpactServiceReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.10 doit etre remplie si 1.1 est un incident majeure reclasse en non-majeure.
        /// </summary>
        internal static string IncidentChamp2_10Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_10Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.10 réussi.
        /// </summary>
        internal static string IncidentChamp2_10Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_10Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.1 est obligatoire.
        /// </summary>
        internal static string IncidentChamp2_1Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_1Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.1 réussi.
        /// </summary>
        internal static string IncidentChamp2_1Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_1Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.2 est non-conforme au format attendu.
        /// </summary>
        internal static string IncidentChamp2_2NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp2_2NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.2 est obligatoire.
        /// </summary>
        internal static string IncidentChamp2_2Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_2Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.2 réussi.
        /// </summary>
        internal static string IncidentChamp2_2Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_2Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.3 est non-conforme au format attendu.
        /// </summary>
        internal static string IncidentChamp2_3NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp2_3NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.3 est obligatoire.
        /// </summary>
        internal static string IncidentChamp2_3Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_3Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.3 réussi.
        /// </summary>
        internal static string IncidentChamp2_3Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_3Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.4 est obligatoire.
        /// </summary>
        internal static string IncidentChamp2_4Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_4Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 2.4 réussi.
        /// </summary>
        internal static string IncidentChamp2_4Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_4Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.2 ne peut pas etre nul dans les rapport intermédiaire et finaux.
        /// </summary>
        internal static string IncidentChamp2_6Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_6Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.9 réussi.
        /// </summary>
        internal static string IncidentChamp2_6Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_6Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.7 ne correspond pas aux valeurs attendus.
        /// </summary>
        internal static string IncidentChamp2_7NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp2_7NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.7 est obligatoire.
        /// </summary>
        internal static string IncidentChamp2_7Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_7Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.7 réussi.
        /// </summary>
        internal static string IncidentChamp2_7Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_7Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.8 est obligatoire.
        /// </summary>
        internal static string IncidentChamp2_8Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_8Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.8 réussi.
        /// </summary>
        internal static string IncidentChamp2_8Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_8Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.9 ne correpond pas aux valeurs attendus..
        /// </summary>
        internal static string IncidentChamp2_9NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp2_9NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 2.9 est obligatoire.
        /// </summary>
        internal static string IncidentChamp2_9Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp2_9Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 2.9 réussi.
        /// </summary>
        internal static string IncidentChamp2_9Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp2_9Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du formattage du champ 3.15 : .
        /// </summary>
        internal static string IncidentChamp3_15Erreur {
            get {
                return ResourceManager.GetString("IncidentChamp3_15Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.15 est obligatoire pour les rapports intermédiaires et finaux.
        /// </summary>
        internal static string IncidentChamp3_15Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp3_15Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.15 réussi.
        /// </summary>
        internal static string IncidentChamp3_15Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp3_15Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.17 est obligatoire si les champs 3.15 ou 3.16 sont specifie.
        /// </summary>
        internal static string IncidentChamp3_17Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp3_17Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champs 3.2 et 3.15 réussi.
        /// </summary>
        internal static string IncidentChamp3_2_3_15Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp3_2_3_15Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.2 est non-conforme au format attendu.
        /// </summary>
        internal static string IncidentChamp3_2NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp3_2NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.2 est obligatoire pour les rapports intermédiaires et finaux.
        /// </summary>
        internal static string IncidentChamp3_2Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp3_2Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.2 réussi.
        /// </summary>
        internal static string IncidentChamp3_2Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp3_2Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 4.10 et 4.11 réussi.
        /// </summary>
        internal static string IncidentChamp4_10Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_10Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.11 doit etre renseigne si le champ 4.10 l&apos;est.
        /// </summary>
        internal static string IncidentChamp4_11Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_11Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 4.13 et 4.14 réussi.
        /// </summary>
        internal static string IncidentChamp4_13_4_14Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_13_4_14Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.13 est au mauvais format.
        /// </summary>
        internal static string IncidentChamp4_13NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_13NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.13 et 4.14 est obligatoire.
        /// </summary>
        internal static string IncidentChamp4_13Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_13Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.14 est au mauvais format.
        /// </summary>
        internal static string IncidentChamp4_14NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_14NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 4.15 et 4.16 réussi.
        /// </summary>
        internal static string IncidentChamp4_15_4_16Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_15_4_16Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.16 est au mauvais format.
        /// </summary>
        internal static string IncidentChamp4_16NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_16NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.16 est obligatoire si le champ 4.15 est renseigné.
        /// </summary>
        internal static string IncidentChamp4_16Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_16Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.1 ne contient pas les valeurs attendus.
        /// </summary>
        internal static string IncidentChamp4_1NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_1NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.1 est obligatoire pour les rapports finaux.
        /// </summary>
        internal static string IncidentChamp4_1Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_1Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 4.1 réussi.
        /// </summary>
        internal static string IncidentChamp4_1Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_1Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 4.2 et 4.3 réussi.
        /// </summary>
        internal static string IncidentChamp4_2_4_3Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_2_4_3Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.2 ne correspond pas aux valeurs attendus.
        /// </summary>
        internal static string IncidentChamp4_2NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_2NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.2 est obligatoire pour les rapports finaux.
        /// </summary>
        internal static string IncidentChamp4_2Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_2Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.3 ne correspond pas aux valeurs attendues.
        /// </summary>
        internal static string IncidentChamp4_3NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_3NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.3 est obligatoire pour certaines valeurs du champ 4.2.
        /// </summary>
        internal static string IncidentChamp4_3Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_3Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.4 est obligatoire si le champ 4.2 renseigne Other.
        /// </summary>
        internal static string IncidentChamp4_4Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_4Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 4.4 réussi.
        /// </summary>
        internal static string IncidentChamp4_4Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_4Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.5 est obligatoire pour les rapport finaux.
        /// </summary>
        internal static string IncidentChamp4_5Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_5Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 4.5 réussi.
        /// </summary>
        internal static string IncidentChamp4_5Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_5Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.6 est obligatoire pour les rapport finaux.
        /// </summary>
        internal static string IncidentChamp4_6Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_6Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 4.6 réussi.
        /// </summary>
        internal static string IncidentChamp4_6Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_6Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.7 est au mauvais format.
        /// </summary>
        internal static string IncidentChamp4_7NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_7NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.7 est obligatoire.
        /// </summary>
        internal static string IncidentChamp4_7Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_7Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 4.7 réussi.
        /// </summary>
        internal static string IncidentChamp4_7Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_7Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.8 est au mauvais format.
        /// </summary>
        internal static string IncidentChamp4_8NonConforme {
            get {
                return ResourceManager.GetString("IncidentChamp4_8NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 4.8 est obligatoire pour les rapports finaux.
        /// </summary>
        internal static string IncidentChamp4_8Obligatoire {
            get {
                return ResourceManager.GetString("IncidentChamp4_8Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du champ 4.8 réussi.
        /// </summary>
        internal static string IncidentChamp4_8Reussite {
            get {
                return ResourceManager.GetString("IncidentChamp4_8Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite complétion Incident.
        /// </summary>
        internal static string IncidentCompletionReussite {
            get {
                return ResourceManager.GetString("IncidentCompletionReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite création Incident.
        /// </summary>
        internal static string IncidentReussite {
            get {
                return ResourceManager.GetString("IncidentReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la lecture des regles json.
        /// </summary>
        internal static string JsonHelperLectureJsonReglesErreur {
            get {
                return ResourceManager.GetString("JsonHelperLectureJsonReglesErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture JSON regles réussi.
        /// </summary>
        internal static string JsonHelperLectureReglesReussite {
            get {
                return ResourceManager.GetString("JsonHelperLectureReglesReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde JSON réussi.
        /// </summary>
        internal static string JsonHelperSauvegardeReussite {
            get {
                return ResourceManager.GetString("JsonHelperSauvegardeReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La devise du rapport (champ 1.15) est invalide.
        /// </summary>
        internal static string ModeleServiceChamp1_15NonConforme {
            get {
                return ResourceManager.GetString("ModeleServiceChamp1_15NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 1.15 est obligatoire.
        /// </summary>
        internal static string ModeleServiceChamp1_15Obligatoire {
            get {
                return ResourceManager.GetString("ModeleServiceChamp1_15Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 1.15 réussi.
        /// </summary>
        internal static string ModeleServiceChamp1_15Reussite {
            get {
                return ResourceManager.GetString("ModeleServiceChamp1_15Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 1.1 est obligatoire.
        /// </summary>
        internal static string ModeleServiceChamp1_1Obligatoire {
            get {
                return ResourceManager.GetString("ModeleServiceChamp1_1Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 1.1 réussi.
        /// </summary>
        internal static string ModeleServiceChamp1_1Reussite {
            get {
                return ResourceManager.GetString("ModeleServiceChamp1_1Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.17 réussi.
        /// </summary>
        internal static string ModeleServiceChamp3_17Reussite {
            get {
                return ResourceManager.GetString("ModeleServiceChamp3_17Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champs 3.31 et 3.32 réussi.
        /// </summary>
        internal static string ModeleServiceChamps3_31_3_32Reussite {
            get {
                return ResourceManager.GetString("ModeleServiceChamps3_31_3_32Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 1er contact ne peut pas etre null.
        /// </summary>
        internal static string PremierContactObligatoire {
            get {
                return ResourceManager.GetString("PremierContactObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.31 est obligaoire pour les rapports intermediaire et finaux et doit utiliser des valeurs predefinies.
        /// </summary>
        internal static string RapportAutoriteObligaoire {
            get {
                return ResourceManager.GetString("RapportAutoriteObligaoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le rapport a autorité est obligatoire : .
        /// </summary>
        internal static string RapportAutoriteObligatoire {
            get {
                return ResourceManager.GetString("RapportAutoriteObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.32 est requis si le champ 3.31 contient Autres.
        /// </summary>
        internal static string RapportAutreAutorite {
            get {
                return ResourceManager.GetString("RapportAutreAutorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite création Rapport.
        /// </summary>
        internal static string RapportReussite {
            get {
                return ResourceManager.GetString("RapportReussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champ 3.23 du type de l&apos;incident non valide.
        /// </summary>
        internal static string TypeIncidentChamp3_23NonConforme {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_23NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.23 est obligatoire.
        /// </summary>
        internal static string TypeIncidentChamp3_23Obligatoire {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_23Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.23 réussi.
        /// </summary>
        internal static string TypeIncidentChamp3_23Reussite {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_23Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ssi le champ 3.23 est other, le champs 3.24 est obligatoire.
        /// </summary>
        internal static string TypeIncidentChamp3_24Obligatoire {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_24Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture champ 3.24 réussi.
        /// </summary>
        internal static string TypeIncidentChamp3_24Reussite {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_24Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si le champs 3.23 contients cyberscurity-related, les champs 3.25 et 3.35 sont obligatoire.
        /// </summary>
        internal static string TypeIncidentChamp3_25_3_35Obligatoire {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_25_3_35Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des champs 3.25 et 3.35 réussi.
        /// </summary>
        internal static string TypeIncidentChamp3_25_3_35Reussite {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_25_3_35Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ 3.25 est non-conforme au valeurs attendus.
        /// </summary>
        internal static string TypeIncidentChamp3_25NonConforme {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_25NonConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si le champ 3.25 est other, le champs 3.26 est obligatoire.
        /// </summary>
        internal static string TypeIncidentChamp3_26Obligatoire {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_26Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture Champ 3.26 réussi.
        /// </summary>
        internal static string TypeIncidentChamp3_26Reussite {
            get {
                return ResourceManager.GetString("TypeIncidentChamp3_26Reussite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réussite création TypeIncident.
        /// </summary>
        internal static string TypeIncidentReussite {
            get {
                return ResourceManager.GetString("TypeIncidentReussite", resourceCulture);
            }
        }
    }
}
